version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: gym-db
    restart: always
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"  # Добавила, чтобы избежать проблем с кодировкой
    ports:
      - "5432:5432"
    volumes:
      - gym_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d # Подключаем папку с миграциями

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Укажите ваш email
      PGADMIN_DEFAULT_PASSWORD: secret          # Укажите ваш пароль
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  gym_data:
