services:
  postgres:
    image: postgres:15
    container_name: EQUIPMENT-db
    restart: always
    environment:
      POSTGRES_DB: EQUIPMENT
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Укажите ваш email
      PGADMIN_DEFAULT_PASSWORD: secret          # Укажите ваш пароль
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  museum_data: