apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-config
  namespace: var12
data:
  SPRING_JPA_SHOW_SQL: "false"
  DB_HOST: "10.60.3.26"
  DB_PORT: "5432"
  DB_NAME: "gym"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://10.60.3.26:5432/gym?currentSchema=public"
  TOMCAT_THREADS: "200"
  MAIN_SERVICE_HOST: "main-service"
  MAIN_SERVICE_PORT: "8080"
  KAFKA_CONCURRENCY: "2"
  SPRING_FLYWAY_ENABLE: "true"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  KAFKA_HOSTS: "10.60.3.27:9094,10.60.3.28:9094"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  RESILIENCE4J_MODE: "retry"  # circuitbreaker
  # For retry
  RETRY_ENABLED: "true"
  RETRY_MAX_ATTEMPTS: "7"
  RETRY_WAIT_DURATION: "10s"

  # For circuitBreaker
  CB_ENABLED: "false"
  CB_FAILURE_RATE: "50"
  CB_WAIT_DURATION: "5s"
  CB_SLIDING_WINDOW: "10"

  CORE_CRASH_DELAY: "10000"

