apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-config
  namespace: var12
data:
  SPRING_JPA_SHOW_SQL: "false"
  DB_HOST: "10.60.3.26"
  DB_PORT: "5432"
  DB_NAME: "gym"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://10.60.3.26:5432/gym?currentSchema=public"
  TOMCAT_THREADS: "200"
  MAIN_SERVICE_HOST: "main-service"
  MAIN_SERVICE_PORT: "8080"
  KAFKA_CONCURRENCY: "2"
  SPRING_FLYWAY_ENABLE: "true"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  KAFKA_HOSTS: "10.60.3.27:9094,10.60.3.28:9094"

