apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: var12
data:
  DDL_AUTO: "validate"
  SHOW_SQL: "false"
  DB_HOST: "host.minikube.internal"
  DB_PORT: "5432"
  DB_NAME: "gym"
  TOMCAT_THREADS: "200"
  CORE_SERVICE_HOST: "main-service"
  CORE_SERVICE_PORT: "8080"
  CORE_SERVICE_TIMEOUT: "60000"
  KAFKA_CONCURRENCY: "2"
  APP_HOST: "0.0.0.0"
  KAFKA_HOSTS: "hl22.zil:9094,hl23.zil:9094"
