apiVersion: apps/v1
kind: Deployment
metadata:
  name: additional-service
  namespace: var12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: additional-service
  template:
    metadata:
      labels:
        app: additional-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: additional-service
          image: klepa300/additional-service:v14.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: apps-config
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"

