apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
  namespace: var12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      hostAliases:
        - ip: "10.60.3.27"
          hostnames:
            - "hl22.zil"
        - ip: "10.60.3.28"
          hostnames:
            - "hl23.zil"
      imagePullSecrets:
        - name: regcred
      containers:
        - name: main-service
          image: klepa300/main-service:v14.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: apps-config
            - secretRef:
                name: db-credentials
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"

