apiVersion: apps/v1
kind: Deployment
metadata:
  name: additional-service
  namespace: var12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: additional-service
  template:
    metadata:
      labels:
        app: additional-service
    spec:
#      nodeSelector:
#        kubernetes.io/hostname: hl12.zil
      imagePullSecrets:
        - name: klepa300
      containers:
        - name: additional-service
          image: klepa300/additional-service:v17.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: apps-config
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"

